'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase/client';
import { panel } from '@/lib/panel';
function Plaza({eventoId,rol,plaza,acceso,editable,onRefresh}){
 const [email,setEmail]=useState(acceso?.email||'');const [vence,setVence]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 async function guardar(e){e.preventDefault();if(acceso&&!window.confirm('¿Reemplazar este acceso? La cuenta anterior dejará de tenerlo.'))return;setBusy(true);setMessage('');try{await panel(createClient(),'asignar',{evento_id:eventoId,rol,plaza,email,vence:rol==='portero'?new Date(vence).toISOString():null});setMessage('Asignación lista. Comparte el enlace de acceso con esa persona.');onRefresh();}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 async function revocar(){if(!window.confirm('¿Revocar este acceso al evento?'))return;setBusy(true);try{await panel(createClient(),'revocar',{evento_id:eventoId,rol,plaza});onRefresh();}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 return <article className="guest-card"><h3>{rol==='titular'?'Titular':'Portero'} {plaza}</h3>{acceso?<><p className="helper" style={{overflowWrap:'anywhere'}}>{acceso.email} · {acceso.user_id?'Aceptado':'Pendiente de aceptación'}{acceso.acceso_vence&&` · Acceso hasta ${new Date(acceso.acceso_vence).toLocaleString('es-MX')}`}</p>{!acceso.user_id&&<p className="helper">Aceptar antes de {new Date(acceso.invitacion_vence).toLocaleString('es-MX')}.</p>}</>:<p className="helper">Espacio disponible.</p>}
 {editable&&<><form onSubmit={guardar}><fieldset disabled={busy} className="grid gap-3"><label>Correo de acceso<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label>{rol==='portero'&&<label>Vigencia del acceso (tu hora local)<input type="datetime-local" required value={vence} onChange={e=>setVence(e.target.value)}/></label>}<button className="dash-primary">{busy?'Guardando…':acceso?'Reemplazar o renovar acceso':'Asignar acceso'}</button></fieldset></form>{acceso&&<div className="row-actions"><button disabled={busy} type="button" onClick={revocar}>Revocar acceso</button><button type="button" onClick={async()=>{try{await navigator.clipboard.writeText(`${window.location.origin}/login`);setMessage('Enlace copiado. Debe entrar con el correo asignado y aceptar desde Mis accesos.');}catch{setMessage('Comparte la dirección de inicio de sesión de Invito.');}}}>Copiar enlace de acceso</button></div>}</>}
 {message&&<p className="helper" role="status">{message}</p>}</article>;
}
export default function EquipoManager({eventoId,accesosIniciales,admin=false}){
 const router=useRouter();return <section><p className="dash-eyebrow">CADA PERSONA, CON SU PROPIO ACCESO</p><h2>Equipo del evento</h2><p className="helper">Hasta dos titulares y dos porteros, incluyendo asignaciones pendientes. Solo Invito puede modificar titulares. Los porteros únicamente registran entradas; su acceso vence en la fecha indicada.</p>{['titular','portero'].map(rol=><div key={rol} className="grid gap-4 md:grid-cols-2 mb-5">{[1,2].map(plaza=>{const acceso=accesosIniciales.find(a=>a.rol===rol&&a.plaza===plaza);return <Plaza key={`${rol}-${plaza}-${acceso?.creado_at||''}`} eventoId={eventoId} rol={rol} plaza={plaza} acceso={acceso} editable={admin||rol==='portero'} onRefresh={()=>router.refresh()}/>;})}</div>)}</section>;
}
