'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase/client';
import { panel } from '@/lib/panel';
import { catalogoPlantillas, modulosDisponibles } from '@/components/invitaciones/plantillas/catalogo';
export default function EventoNegocio({evento,negocio}){
 const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const router=useRouter();
 async function guardar(e){e.preventDefault();const form=new FormData(e.currentTarget);const datos=Object.fromEntries(form);datos.modulos=Object.fromEntries(modulosDisponibles.map(([key])=>[key,form.has(`modulo_${key}`)]));setBusy(true);setMessage('');try{await panel(createClient(),'negocio',{...datos,evento_id:evento.id,version:1});setMessage('Configuración guardada.');router.refresh();}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 return <form onSubmit={guardar} className="guest-card mb-6"><h2>Entrega y seguimiento comercial</h2><fieldset disabled={busy} className="grid gap-4 md:grid-cols-2 mt-5"><label>Publicación<select name="publicacion" defaultValue={evento.publicacion}><option value="borrador">Borrador</option><option value="publicado">Publicado</option><option value="archivado">Archivado</option></select></label><label>Trabajo<select name="trabajo" defaultValue={negocio?.trabajo}><option value="por_preparar">Por preparar</option><option value="en_revision">En revisión</option><option value="entregado">Entregado</option></select></label><label>Precio acordado (MXN)<input name="precio" type="number" min="0" step="0.01" required defaultValue={negocio?.precio??1490}/></label><label>Total abonado (MXN)<input name="abonado" type="number" min="0" step="0.01" required defaultValue={negocio?.abonado??0}/></label><label>Plantilla<select name="plantilla" defaultValue={evento.plantilla}>{catalogoPlantillas.map(p=><option key={p.id} value={p.id}>{p.nombre} · v{p.version}</option>)}</select></label><label>Notas internas<textarea name="notas" rows={3} defaultValue={negocio?.notas}/></label><div className="md:col-span-2"><h3>Secciones de la invitación</h3><div className="grid gap-3 sm:grid-cols-2 mt-4">{modulosDisponibles.map(([key,label])=><label key={key}><input type="checkbox" name={`modulo_${key}`} defaultChecked={evento.modulos_activos?.[key]!==false}/>{label}</label>)}</div></div><button className="dash-primary">{busy?'Guardando…':'Guardar configuración'}</button></fieldset><p className="helper">Los importes son un registro manual. Los clientes no pueden ver estas notas ni cambiar la plantilla.</p>{message&&<p role="status">{message}</p>}</form>;
}
